name: Ephemeral Electrons
description: A code is a thought, just another stream of ephemeral electrons
avatar: https://avatars0.githubusercontent.com/u/2162408?s=460&v=4

footer-links:
  github: tmzh/tmzh.github.io
  twitter: t4m1zh

google_analytics: UA-108447382-1

url: https://tmzh.github.io/

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'syntax'

sass:
  style: :expanded

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

excerpt_separator: "<!--more-->"